### PR TITLE
style: apply isort formatting

### PR DESCRIPTION
**Pull request by redeboer**
Just a recommendation that is used by many projects. @ianhi, check out the effect with

```bash
pre-commit run isort -a
```

If you like it, push the changes to this branch and CI will pass again.

### CODE REVIEW

**Comment by redeboer** [comment]
I noticed now that `pre-commit` is not run as a CI check, but that (only) black is checked separately through a GitHub action

https://github.com/ianhi/mpl-interactions/blob/6fc9482cf713c89e5d22f145209481258da0b894/.github/workflows/lint.yml#L7-L13

I suggest to use https://pre-commit.ci instead of that action and instead of c7fb57a, as pre-commit.ci is faster.

**Comment by ianhi** [comment]
> I suggest to use https://pre-commit.ci instead of that action and instead of c7fb57a, as pre-commit.ci is faster.

Should have just installed this and looks like it's working (https://github.com/ianhi/mpl-interactions/pull/205)

**Comment by ianhi** [comment]
Also `mpl-latest` is failing due to upstream issues: https://github.com/matplotlib/ipympl/issues/335

**Comment by redeboer** [comment]
> Should have just installed this and looks like it's working (#205)

Ok cool, thanks! Yep it's working ca2f71d

**Comment by ianhi** [comment]
awesome thanks!

**Pull request merged**
