### PR TITLE
docs!: switch to sphinx-book-theme

### PR DESCRIPTION
**Pull request by redeboer**
Documentation is now built with the [sphinx-book-theme](https://sphinx-book-theme.readthedocs.io). Main reason is that it works much better for Jupyter notebooks, particular in combination with [sphinx-thebe](https://sphinx-thebe.readthedocs.io). That solves the `nbsphinx_prolog` issue mentioned in #208.

**Have a look at the preview [here](https://mpl-interactions--209.org.readthedocs.build/en/209)**

Some related changes:
- e50d6bf The `examples` folder had to be moved to `docs`, because the launch buttons then lead you directly to the correct notebook on Binder.
- e50d6bf also removes the gifmaker
- Added [nbQA](https://github.com/nbQA-dev/nbQA) formatting and [nbstripout](https://github.com/kynan/nbstripout)
- e6fed31 Updated Contribute instructions (see https://github.com/ianhi/mpl-interactions/pull/203#issuecomment-884471611)
- cc749c4 Shortened the URLs

### CODE REVIEW

**Comment by redeboer** [comment]
@ianhi Related to `057866a`, check out [ReviewNB](https://www.reviewnb.com)

**Comment by ianhi** [comment]
> @ianhi Related to 057866a, check out ReviewNB

Been meaning to do this. Thanks for the push towards this - done.



> Added nbQA formatting and nbstripout

Actually just discovered nbQA because it's author just starred this repo :open_mouth: - looks great big supporter of this

image


--- 

Will look at this more thoroughly tomorrow. and again deep thanks for all the wonderful work

**Comment by MarcoGorelli** [comment]
> Actually just discovered nbQA because it's author just starred this repo 😮 - looks great big supporter of this

😆  incidentally I discovered `mpl-interactions` because `nbQA` was mentioned here - I love matplotlib and Jupyter notebooks so this is extremely useful, thanks for your work on this!

**Comment by ianhi** [comment]
> Will look at this more thoroughly tomorrow. and again deep thanks for all the wonderful work

This has been an uhhhh extremely permissive definition of tomorrow :( Sorry about that, looking now!


> e50d6bf also removes the gifmaker

I guess this may be down to personal preference but I don't love this. I did this because I wanted the docs to be different as presented in the docs vs when used interactively. So for example in https://mybinder.org/v2/gh/redeboer/mpl-interactions/sphinx-book-theme?urlpath=lab/tree/docs/examples/ when you run the cells you end up with the GIF and the actual interactive output. Overall it's just a small nit though and this is great so I'm going to go ahead and merge - thank you again!

As an aside I think the ultimate solution to interactive docs here is not to muck around with recording and embedding gifs but to have the whole docs be interactive using:  [jupyterlite](https://jupyterlite.readthedocs.io/en/latest/) (wasm powered full python kernel) which may be achievable via https://jupyterlite.readthedocs.io/en/latest/deploying.html?highlight=sphinx but that's probably a project for another day.

**Review by ianhi — APPROVED** [review]
:tada:

**Comment by redeboer** [comment]
> This has been an uhhhh extremely permissive definition of tomorrow :( Sorry about that, looking now!

Hahaha no worries :sweat_smile: 

> I guess this may be down to personal preference but I don't love this. I did this because I wanted the docs to be different as presented in the docs vs when used interactively. So for example in https://mybinder.org/v2/gh/redeboer/mpl-interactions/sphinx-book-theme?urlpath=lab/tree/docs/examples/ when you run the cells you end up with the GIF and the actual interactive output. Overall it's just a small nit though and this is great so I'm going to go ahead and merge - thank you again!
> 
> As an aside I think the ultimate solution to interactive docs here is not to muck around with recording and embedding gifs but to have the whole docs be interactive using: [jupyterlite](https://jupyterlite.readthedocs.io/en/latest/) (wasm powered full python kernel) which may be achievable via https://jupyterlite.readthedocs.io/en/latest/deploying.html?highlight=sphinx but that's probably a project for another day.

Thanks for writing out your thoughts here! I also need some easier way to have this interactivity directly available in the browser, so I'd also be interested in something like jupyterlite. But for now, as you say, it is indeed more a matter of preference of how to get these gifs in the docs. I think in terms of maintenance it is a bit clearer if the gifs are explicitly added through the markdown rather than the (less accessible) cell metadata and further logic that is implemented in the `conf.py`.

**Comment by ianhi** [comment]
Some relevant issues:

https://github.com/executablebooks/thebe/issues/412
Recently active: https://github.com/executablebooks/thebe/issues/465
https://github.com/pyodide/pyodide/issues/1713
https://github.com/jupyterlite/jupyterlite/issues/149

**Pull request merged**
