### PR TITLE
ci: detect doctests with pytest

### LINKED ISSUE #210: Detect and run doctests with pytest
When running `pytest --collect-only` (which happens for instance when you want to explore the tests in VSCode), some matplotlib plots are created. This means there is some code that is not within a (test) function, which slows down test discovery.

### PR DESCRIPTION
**Pull request by redeboer**
Closes #210

Bit of a trivial one -- but potentially makes live easier

### CODE REVIEW

**Comment by redeboer** [comment]
Just noticed that the tests are installed with the package. Is that supposed to be the case?

**Comment by ianhi** [comment]
You mean here?:
https://github.com/ianhi/mpl-interactions/blob/bb5f7f21925c2a0068e672c9cdc0f08b97f9da95/MANIFEST.in#L21-L23

That's because I based that on the manifest from the jupyter widget cookiecutter https://github.com/jupyter-widgets/widget-ts-cookiecutter/blob/f8c4f1d2c61374811423eb724b9eb11c6e2f10b1/%7B%7Bcookiecutter.github_project_name%7D%7D/MANIFEST.in#L23-L25 and subsequently never thought about it.

**Comment by redeboer** [comment]
> You mean here?

No afaik the manifest tells what is to be shipped in the source code on e.g. pypi
https://pypi.org/project/mpl-interactions/#files

I mean that when you `pip install mpl-interactions`, you will also see tests in the install folder. Reason is that the tests are in the source code folder and then setuptools will consider them part of the package:
https://github.com/ianhi/mpl-interactions/blob/b5bdb420d0d53c46db823a8734b685f0e386678e/setup.cfg#L38

Pytest suggests this layout, optionally also with the source code under `src`:
https://docs.pytest.org/en/latest/explanation/goodpractices.html#tests-outside-application-code

**Comment by ianhi** [comment]
thanks!

**Pull request merged**
